[2024-04-15T13:02:04.859+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T13:02:04.970+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: eksplorasii_dag.create_fruits_table manual__2024-04-15T13:01:40.648638+00:00 [queued]>
[2024-04-15T13:02:04.987+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: eksplorasii_dag.create_fruits_table manual__2024-04-15T13:01:40.648638+00:00 [queued]>
[2024-04-15T13:02:04.988+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-15T13:02:05.025+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): create_fruits_table> on 2024-04-15 13:01:40.648638+00:00
[2024-04-15T13:02:05.055+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2978) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T13:02:05.058+0000] {standard_task_runner.py:63} INFO - Started process 2980 to run task
[2024-04-15T13:02:05.057+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'eksplorasii_dag', 'create_fruits_table', 'manual__2024-04-15T13:01:40.648638+00:00', '--job-id', '501', '--raw', '--subdir', 'DAGS_FOLDER/eksplorasii_dag.py', '--cfg-path', '/tmp/tmpedp_jund']
[2024-04-15T13:02:05.061+0000] {standard_task_runner.py:91} INFO - Job 501: Subtask create_fruits_table
[2024-04-15T13:02:05.162+0000] {task_command.py:426} INFO - Running <TaskInstance: eksplorasii_dag.create_fruits_table manual__2024-04-15T13:01:40.648638+00:00 [running]> on host 2354a2c4893f
[2024-04-15T13:02:05.467+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abdan' AIRFLOW_CTX_DAG_ID='eksplorasii_dag' AIRFLOW_CTX_TASK_ID='create_fruits_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T13:01:40.648638+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-15T13:01:40.648638+00:00'
[2024-04-15T13:02:05.485+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T13:02:05.486+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS fruits (
            id SERIAL PRIMARY KEY,
            name VARCHAR(50) NOT NULL,
            calories DECIMAL NOT NULL,
            fat DECIMAL NOT NULL,
            sugar DECIMAL NOT NULL,
            carbohydrates DECIMAL NOT NULL,
            protein DECIMAL NOT NULL
        );

        CREATE SEQUENCE IF NOT EXISTS fruits_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1;
    
[2024-04-15T13:02:05.611+0000] {base.py:84} INFO - Using connection ID 'eksplorasi_db' for task execution.
[2024-04-15T13:02:05.682+0000] {base.py:84} INFO - Using connection ID 'eksplorasi_db' for task execution.
[2024-04-15T13:02:05.694+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T13:02:05.697+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-04-15T13:02:16.218+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 501 for task create_fruits_table ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 2980)
[2024-04-15T13:02:26.111+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-15T13:02:26.157+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-04-15T13:02:26.192+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T13:02:26.206+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
