[2024-04-13T16:08:47.879+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-13T16:08:47.905+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prioritas1_no2.calculate_sum scheduled__2024-04-12T00:00:00+00:00 [queued]>
[2024-04-13T16:08:47.913+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prioritas1_no2.calculate_sum scheduled__2024-04-12T00:00:00+00:00 [queued]>
[2024-04-13T16:08:47.914+0000] {taskinstance.py:2303} INFO - Starting attempt 5 of 6
[2024-04-13T16:08:47.931+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): calculate_sum> on 2024-04-12 00:00:00+00:00
[2024-04-13T16:08:47.939+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=412) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-13T16:08:47.941+0000] {standard_task_runner.py:63} INFO - Started process 414 to run task
[2024-04-13T16:08:47.941+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'prioritas1_no2', 'calculate_sum', 'scheduled__2024-04-12T00:00:00+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/nomer2_dag.py', '--cfg-path', '/tmp/tmpkrjg2p1m']
[2024-04-13T16:08:47.944+0000] {standard_task_runner.py:91} INFO - Job 226: Subtask calculate_sum
[2024-04-13T16:08:47.999+0000] {task_command.py:426} INFO - Running <TaskInstance: prioritas1_no2.calculate_sum scheduled__2024-04-12T00:00:00+00:00 [running]> on host a8c8062a752a
[2024-04-13T16:08:48.136+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abdan' AIRFLOW_CTX_DAG_ID='prioritas1_no2' AIRFLOW_CTX_TASK_ID='calculate_sum' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-12T00:00:00+00:00'
[2024-04-13T16:08:48.139+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-13T16:08:48.153+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-13T16:08:48.154+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/nomer2_dag.py", line 16, in calculate_sum
    if not all(isinstance(angka, int) and angka.isnumeric() for angka in angka_acak):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/nomer2_dag.py", line 16, in <genexpr>
    if not all(isinstance(angka, int) and angka.isnumeric() for angka in angka_acak):
                                          ^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'isnumeric'
[2024-04-13T16:08:48.172+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=prioritas1_no2, task_id=calculate_sum, execution_date=20240412T000000, start_date=20240413T160847, end_date=20240413T160848
[2024-04-13T16:08:48.198+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 226 for task calculate_sum ('int' object has no attribute 'isnumeric'; 414)
[2024-04-13T16:08:48.235+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-13T16:08:48.268+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-13T16:08:48.288+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
