[2024-04-14T12:00:22.842+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: fruits_data_pipeline.create_fruits_table scheduled__2024-04-13T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-04-14T12:14:56.660+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: fruits_data_pipeline.create_fruits_table scheduled__2024-04-13T00:00:00+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
