[2024-04-12T13:08:16.627+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-12T13:08:16.663+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: eksplorasi.create_fruits_table manual__2024-04-12T12:55:56.795094+00:00 [queued]>
[2024-04-12T13:08:16.683+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: eksplorasi.create_fruits_table manual__2024-04-12T12:55:56.795094+00:00 [queued]>
[2024-04-12T13:08:16.685+0000] {taskinstance.py:2303} INFO - Starting attempt 6 of 10
[2024-04-12T13:08:16.723+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): create_fruits_table> on 2024-04-12 12:55:56.795094+00:00
[2024-04-12T13:08:16.746+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1240) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-12T13:08:16.748+0000] {standard_task_runner.py:63} INFO - Started process 1242 to run task
[2024-04-12T13:08:16.747+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'eksplorasi', 'create_fruits_table', 'manual__2024-04-12T12:55:56.795094+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/eksplorasi_dag.py', '--cfg-path', '/tmp/tmp6xwfrqot']
[2024-04-12T13:08:16.751+0000] {standard_task_runner.py:91} INFO - Job 181: Subtask create_fruits_table
[2024-04-12T13:08:16.851+0000] {task_command.py:426} INFO - Running <TaskInstance: eksplorasi.create_fruits_table manual__2024-04-12T12:55:56.795094+00:00 [running]> on host 805e8d5936d1
[2024-04-12T13:08:17.169+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abdan' AIRFLOW_CTX_DAG_ID='eksplorasi' AIRFLOW_CTX_TASK_ID='create_fruits_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T12:55:56.795094+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-12T12:55:56.795094+00:00'
[2024-04-12T13:08:17.175+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-12T13:08:17.176+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE fruits (
            id BIGSERIAL PRIMARY KEY,
            name VARCHAR(255),
            calories DECIMAL,
            fat DECIMAL,
            sugar DECIMAL,
            carbohydrates DECIMAL,
            protein DECIMAL
        );
        
[2024-04-12T13:08:17.203+0000] {base.py:84} INFO - Using connection ID 'my_postgres' for task execution.
[2024-04-12T13:08:17.234+0000] {base.py:84} INFO - Using connection ID 'my_postgres' for task execution.
[2024-04-12T13:08:17.247+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-12T13:08:17.248+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "postgres" (172.29.0.4), port 5432 failed: fe_sendauth: no password supplied

[2024-04-12T13:08:17.283+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=eksplorasi, task_id=create_fruits_table, execution_date=20240412T125556, start_date=20240412T130816, end_date=20240412T130817
[2024-04-12T13:08:17.335+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 181 for task create_fruits_table (connection to server at "postgres" (172.29.0.4), port 5432 failed: fe_sendauth: no password supplied
; 1242)
[2024-04-12T13:08:17.379+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-12T13:08:17.393+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class SimpleHttpOperator. (Class `SimpleHttpOperator` is deprecated and will be removed in a future release. Please use `HttpOperator` instead.)
  result = cls.__new__(cls)

[2024-04-12T13:08:17.394+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-04-12T13:08:17.418+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-12T13:08:17.441+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
