[2024-04-11T12:30:36.719+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: prioritas1_no1.echo_hello_airflow scheduled__2024-04-09T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-04-12T00:48:59.942+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: prioritas1_no1.echo_hello_airflow scheduled__2024-04-09T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
