[2024-04-12T11:54:51.765+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: prioritas2.write_to_txt manual__2024-04-12T11:43:54.463606+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
