[2024-04-15T10:04:39.140+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T10:04:39.163+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prioritas1_no2.calculate_sum scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T10:04:39.171+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prioritas1_no2.calculate_sum scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T10:04:39.172+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-15T10:04:39.190+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): calculate_sum> on 2024-04-14 00:00:00+00:00
[2024-04-15T10:04:39.202+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=256) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T10:04:39.210+0000] {standard_task_runner.py:63} INFO - Started process 259 to run task
[2024-04-15T10:04:39.204+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'prioritas1_no2', 'calculate_sum', 'scheduled__2024-04-14T00:00:00+00:00', '--job-id', '297', '--raw', '--subdir', 'DAGS_FOLDER/nomer2_dag.py', '--cfg-path', '/tmp/tmp3ck3ymjo']
[2024-04-15T10:04:39.212+0000] {standard_task_runner.py:91} INFO - Job 297: Subtask calculate_sum
[2024-04-15T10:04:39.262+0000] {task_command.py:426} INFO - Running <TaskInstance: prioritas1_no2.calculate_sum scheduled__2024-04-14T00:00:00+00:00 [running]> on host 2354a2c4893f
[2024-04-15T10:04:39.348+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abdan' AIRFLOW_CTX_DAG_ID='prioritas1_no2' AIRFLOW_CTX_TASK_ID='calculate_sum' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-14T00:00:00+00:00'
[2024-04-15T10:04:39.350+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T10:04:39.360+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T10:04:39.361+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/nomer2_dag.py", line 16, in calculate_sum
    if not all(isinstance(angka, int) and angka.isnumeric() for angka in angka_acak):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/nomer2_dag.py", line 16, in <genexpr>
    if not all(isinstance(angka, int) and angka.isnumeric() for angka in angka_acak):
                                          ^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'isnumeric'
[2024-04-15T10:04:39.372+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=prioritas1_no2, task_id=calculate_sum, execution_date=20240414T000000, start_date=20240415T100439, end_date=20240415T100439
[2024-04-15T10:04:39.387+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 297 for task calculate_sum ('int' object has no attribute 'isnumeric'; 259)
[2024-04-15T10:04:39.425+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-15T10:04:39.445+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T10:04:39.453+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
